{
 "title": "Calendar Services",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CreateEvent [RPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_api_CreateEvent_count[5m])"
    }
   ]
  },
  {
   "title": "CreateEvent [Latency]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "calendar_api_CreateEvent" }
   ]
  },
  {
   "title": "DeleteEvent [RPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_api_DeleteEvent_count[5m])"
    }
   ]
  },
  {
   "title": "DeleteEvent [Latency]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "calendar_api_DeleteEvent" }
   ]
  },
  {
   "title": "GetEvents [RPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_api_GetEvents_count[5m])"
    }
   ]
  },
  {
   "title": "GetEvents [Latency]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "calendar_api_GetEvents" }
   ]
  },
  {
   "title": "EditEvents [RPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_api_EditEvent_count[5m])"
    }
   ]
  },
  {
   "title": "EditEvents[Latency]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "calendar_api_EditEvent" }
   ]
  },
  {
   "title": "Events created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"calendar\"}"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(calendar_api_Errors[5m])" }
   ]
  },
  {
   "title": "Notifications [RPS]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(calendar_sender_Send[5m])" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"calendar\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname=\"calendar\"}"
    }
   ]
  }
 ]
}