// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimePeriod int32

const (
	TimePeriod_TIME_UNKNOWN TimePeriod = 0
	TimePeriod_TIME_DAY     TimePeriod = 1
	TimePeriod_TIME_WEEK    TimePeriod = 2
	TimePeriod_TIME_MONTH   TimePeriod = 3
)

var TimePeriod_name = map[int32]string{
	0: "TIME_UNKNOWN",
	1: "TIME_DAY",
	2: "TIME_WEEK",
	3: "TIME_MONTH",
}

var TimePeriod_value = map[string]int32{
	"TIME_UNKNOWN": 0,
	"TIME_DAY":     1,
	"TIME_WEEK":    2,
	"TIME_MONTH":   3,
}

func (x TimePeriod) String() string {
	return proto.EnumName(TimePeriod_name, int32(x))
}

func (TimePeriod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type CreateEventRequest struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string               `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Notify               *duration.Duration   `protobuf:"bytes,6,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateEventRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateEventRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateEventRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *CreateEventRequest) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *CreateEventRequest) GetNotify() *duration.Duration {
	if m != nil {
		return m.Notify
	}
	return nil
}

type CreateEventResponse struct {
	// Types that are valid to be assigned to Result:
	//	*CreateEventResponse_Event
	//	*CreateEventResponse_Error
	Result               isCreateEventResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

type isCreateEventResponse_Result interface {
	isCreateEventResponse_Result()
}

type CreateEventResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type CreateEventResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateEventResponse_Event) isCreateEventResponse_Result() {}

func (*CreateEventResponse_Error) isCreateEventResponse_Result() {}

func (m *CreateEventResponse) GetResult() isCreateEventResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateEventResponse) GetEvent() *Event {
	if x, ok := m.GetResult().(*CreateEventResponse_Event); ok {
		return x.Event
	}
	return nil
}

func (m *CreateEventResponse) GetError() string {
	if x, ok := m.GetResult().(*CreateEventResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateEventResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateEventResponse_Event)(nil),
		(*CreateEventResponse_Error)(nil),
	}
}

type EditEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEventRequest) Reset()         { *m = EditEventRequest{} }
func (m *EditEventRequest) String() string { return proto.CompactTextString(m) }
func (*EditEventRequest) ProtoMessage()    {}
func (*EditEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *EditEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEventRequest.Unmarshal(m, b)
}
func (m *EditEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEventRequest.Marshal(b, m, deterministic)
}
func (m *EditEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEventRequest.Merge(m, src)
}
func (m *EditEventRequest) XXX_Size() int {
	return xxx_messageInfo_EditEventRequest.Size(m)
}
func (m *EditEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditEventRequest proto.InternalMessageInfo

func (m *EditEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EditEventResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditEventResponse) Reset()         { *m = EditEventResponse{} }
func (m *EditEventResponse) String() string { return proto.CompactTextString(m) }
func (*EditEventResponse) ProtoMessage()    {}
func (*EditEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *EditEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEventResponse.Unmarshal(m, b)
}
func (m *EditEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEventResponse.Marshal(b, m, deterministic)
}
func (m *EditEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEventResponse.Merge(m, src)
}
func (m *EditEventResponse) XXX_Size() int {
	return xxx_messageInfo_EditEventResponse.Size(m)
}
func (m *EditEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditEventResponse proto.InternalMessageInfo

func (m *EditEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventRequest) Reset()         { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()    {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *DeleteEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequest.Unmarshal(m, b)
}
func (m *DeleteEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequest.Merge(m, src)
}
func (m *DeleteEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequest.Size(m)
}
func (m *DeleteEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequest proto.InternalMessageInfo

func (m *DeleteEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteEventResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventResponse) Reset()         { *m = DeleteEventResponse{} }
func (m *DeleteEventResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEventResponse) ProtoMessage()    {}
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DeleteEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventResponse.Unmarshal(m, b)
}
func (m *DeleteEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventResponse.Merge(m, src)
}
func (m *DeleteEventResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEventResponse.Size(m)
}
func (m *DeleteEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventResponse proto.InternalMessageInfo

func (m *DeleteEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetEventsRequest struct {
	Period               TimePeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=TimePeriod" json:"period,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetPeriod() TimePeriod {
	if m != nil {
		return m.Period
	}
	return TimePeriod_TIME_UNKNOWN
}

func (m *GetEventsRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *GetEventsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("TimePeriod", TimePeriod_name, TimePeriod_value)
	proto.RegisterType((*CreateEventRequest)(nil), "CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "CreateEventResponse")
	proto.RegisterType((*EditEventRequest)(nil), "EditEventRequest")
	proto.RegisterType((*EditEventResponse)(nil), "EditEventResponse")
	proto.RegisterType((*DeleteEventRequest)(nil), "DeleteEventRequest")
	proto.RegisterType((*DeleteEventResponse)(nil), "DeleteEventResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "GetEventsResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x6d, 0x52, 0x1a, 0xad, 0x5f, 0x46, 0x95, 0x7e, 0xad, 0x50, 0x88, 0xd0, 0xa8, 0x0c, 0x17,
	0x03, 0x24, 0x4f, 0x14, 0xb8, 0x80, 0x2b, 0xb6, 0xb5, 0x62, 0x53, 0xb5, 0x0e, 0x45, 0x45, 0x15,
	0xdc, 0x4c, 0x19, 0xf1, 0x26, 0x4b, 0x5d, 0x1c, 0x1c, 0x17, 0xc4, 0x13, 0xf0, 0xbc, 0xbc, 0x01,
	0x8a, 0xe3, 0x74, 0x69, 0x32, 0x81, 0xb8, 0x3c, 0xdf, 0xdf, 0x39, 0x3a, 0xc7, 0x86, 0x6e, 0x94,
	0x72, 0x9a, 0x4a, 0xa1, 0x44, 0xe0, 0xb2, 0xef, 0x2c, 0x51, 0x06, 0x3c, 0xbe, 0x16, 0xe2, 0x7a,
	0xc5, 0x0e, 0x34, 0xba, 0x5c, 0x5f, 0x1d, 0x28, 0x7e, 0xc3, 0x32, 0x15, 0xdd, 0xa4, 0x66, 0x60,
	0xaf, 0x3e, 0x10, 0xaf, 0x65, 0xa4, 0xb8, 0x48, 0x8a, 0x3e, 0xf9, 0x65, 0x03, 0x1e, 0x4b, 0x16,
	0x29, 0x36, 0xcd, 0xcf, 0x86, 0xec, 0xdb, 0x9a, 0x65, 0x0a, 0x87, 0xd0, 0x51, 0x5c, 0xad, 0x98,
	0x6f, 0x8d, 0xac, 0xfd, 0x6e, 0x58, 0x00, 0x1c, 0x81, 0x1b, 0xb3, 0xec, 0xab, 0xe4, 0x69, 0x7e,
	0xc1, 0xb7, 0x75, 0xaf, 0x5a, 0xca, 0xf7, 0xc4, 0x8f, 0x84, 0x49, 0xbf, 0x5d, 0xec, 0x69, 0x80,
	0x6f, 0x01, 0x32, 0x15, 0x49, 0x75, 0x91, 0xab, 0xf3, 0xef, 0x8d, 0xac, 0x7d, 0x77, 0x1c, 0xd0,
	0x42, 0x19, 0x2d, 0x95, 0xd1, 0x45, 0x29, 0x3d, 0xec, 0xea, 0xe9, 0x1c, 0xe3, 0x1b, 0xd8, 0x29,
	0x15, 0xfb, 0x1d, 0xbd, 0xf8, 0xb0, 0xb1, 0x38, 0x31, 0x03, 0xe1, 0x66, 0x14, 0x5f, 0x82, 0x93,
	0x08, 0xc5, 0xaf, 0x7e, 0xfa, 0xce, 0xbf, 0x96, 0xcc, 0x20, 0x59, 0xc2, 0x60, 0xcb, 0x88, 0x2c,
	0x15, 0x49, 0xc6, 0x70, 0x0f, 0x3a, 0xda, 0x70, 0xed, 0x84, 0x3b, 0x76, 0xa8, 0x6e, 0x9f, 0xb4,
	0xc2, 0xa2, 0x8c, 0x0f, 0xa0, 0xc3, 0xa4, 0x14, 0xb2, 0x70, 0x43, 0xd7, 0x73, 0x78, 0xb4, 0x03,
	0x8e, 0x64, 0xd9, 0x7a, 0xa5, 0xc8, 0x7b, 0xf0, 0xa6, 0x31, 0x57, 0x5b, 0xfe, 0xf6, 0xc0, 0xe6,
	0xb1, 0x31, 0xd7, 0xe6, 0x31, 0x3e, 0x2a, 0x59, 0xec, 0x2a, 0x8b, 0xe1, 0x20, 0xcf, 0xa0, 0x5f,
	0xb9, 0x60, 0x84, 0x0d, 0x4b, 0x62, 0x13, 0x91, 0x06, 0xe4, 0x29, 0xe0, 0x84, 0xad, 0x58, 0x2d,
	0xce, 0x1a, 0x1d, 0x79, 0x01, 0x83, 0xad, 0xa9, 0xbf, 0x9e, 0x94, 0xe0, 0x7d, 0x60, 0x05, 0x79,
	0x56, 0x1e, 0x7c, 0x02, 0x4e, 0xca, 0x24, 0x17, 0xc5, 0xd1, 0xde, 0xd8, 0xd5, 0xe9, 0x7d, 0xd4,
	0xa5, 0xd0, 0xb4, 0x6a, 0xb1, 0xdb, 0xff, 0x11, 0x3b, 0x39, 0x85, 0x7e, 0x85, 0x73, 0x13, 0x85,
	0xa3, 0xfd, 0xc8, 0x7c, 0x6b, 0xd4, 0xae, 0xb8, 0x64, 0xaa, 0xb7, 0xf2, 0xed, 0x8a, 0xfc, 0xe7,
	0x33, 0x80, 0x5b, 0x6d, 0xe8, 0xc1, 0xee, 0xe2, 0xf4, 0x6c, 0x7a, 0xf1, 0x69, 0x3e, 0x9b, 0x9f,
	0x2f, 0xe7, 0x5e, 0x0b, 0x77, 0x61, 0x47, 0x57, 0x26, 0x87, 0x9f, 0x3d, 0x0b, 0xef, 0x43, 0x57,
	0xa3, 0xe5, 0x74, 0x3a, 0xf3, 0x6c, 0xec, 0x01, 0x68, 0x78, 0x76, 0x3e, 0x5f, 0x9c, 0x78, 0xed,
	0xf1, 0x6f, 0x0b, 0xdc, 0xe3, 0x68, 0xc5, 0x92, 0x38, 0x92, 0x87, 0x29, 0xc7, 0x77, 0xe0, 0x56,
	0x1e, 0x0d, 0x0e, 0x68, 0xf3, 0x2f, 0x05, 0x43, 0x7a, 0xc7, 0xbb, 0x22, 0x2d, 0x7c, 0x0d, 0xdd,
	0x4d, 0xaa, 0xd8, 0xa7, 0xf5, 0x37, 0x12, 0x20, 0x6d, 0x84, 0x4e, 0x5a, 0x39, 0x63, 0x25, 0x3a,
	0x1c, 0xd0, 0x66, 0xdc, 0xc1, 0x90, 0xde, 0x91, 0x6e, 0xc1, 0xb8, 0x71, 0x15, 0xfb, 0xb4, 0x9e,
	0x6a, 0x80, 0xb4, 0x61, 0x3a, 0x69, 0x1d, 0x75, 0xbe, 0xb4, 0xa3, 0x94, 0x5f, 0x3a, 0x3a, 0xb1,
	0x57, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x32, 0xc0, 0x9c, 0x8b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalendarApiClient is the client API for CalendarApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarApiClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	EditEvent(ctx context.Context, in *EditEventRequest, opts ...grpc.CallOption) (*EditEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type calendarApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarApiClient(cc grpc.ClientConnInterface) CalendarApiClient {
	return &calendarApiClient{cc}
}

func (c *calendarApiClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/CalendarApi/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarApiClient) EditEvent(ctx context.Context, in *EditEventRequest, opts ...grpc.CallOption) (*EditEventResponse, error) {
	out := new(EditEventResponse)
	err := c.cc.Invoke(ctx, "/CalendarApi/EditEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarApiClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, "/CalendarApi/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarApiClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/CalendarApi/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarApiServer is the server API for CalendarApi service.
type CalendarApiServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	EditEvent(context.Context, *EditEventRequest) (*EditEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
}

// UnimplementedCalendarApiServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarApiServer struct {
}

func (*UnimplementedCalendarApiServer) CreateEvent(ctx context.Context, req *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedCalendarApiServer) EditEvent(ctx context.Context, req *EditEventRequest) (*EditEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditEvent not implemented")
}
func (*UnimplementedCalendarApiServer) DeleteEvent(ctx context.Context, req *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedCalendarApiServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterCalendarApiServer(s *grpc.Server, srv CalendarApiServer) {
	s.RegisterService(&_CalendarApi_serviceDesc, srv)
}

func _CalendarApi_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarApiServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CalendarApi/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarApiServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarApi_EditEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarApiServer).EditEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CalendarApi/EditEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarApiServer).EditEvent(ctx, req.(*EditEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarApi_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarApiServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CalendarApi/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarApiServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarApi_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarApiServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CalendarApi/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarApiServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalendarApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CalendarApi",
	HandlerType: (*CalendarApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _CalendarApi_CreateEvent_Handler,
		},
		{
			MethodName: "EditEvent",
			Handler:    _CalendarApi_EditEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _CalendarApi_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _CalendarApi_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
