---
db:
  user: "dbuser"
  password: "En9NR2b869"
  host: "127.0.0.1"
  port: 5432
  database: "calendar"
grpc_listen:
  ip: "0.0.0.0"
  port: 50051
log:
  log_file: ./calendar.log
  log_level: debug
