version: "3"

networks:
  monitor-net:
    driver: bridge

#volumes:
#  prometheus_data: {}
#  grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=200h'
    # restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net

#  grafana:
#    image: grafana/grafana:latest-ubuntu
#    container_name: grafana
#    volumes:
#      - grafana_data:/var/lib/grafana
#      - ./grafana/datasources:/etc/grafana/datasources
#      - ./grafana/dashboards:/etc/grafana/dashboards
#      - ./grafana/setup.sh:/setup.sh
#    entrypoint: /setup.sh
#    user: root
#    environment:
#      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
#      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
#      - GF_USERS_ALLOW_SIGN_UP=false
#    restart: unless-stopped
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
#    networks:
#      - monitor-net